### ISSUE TITLE
Sintaks Blogger Baru

### ISSUE THREAD

**Issue by tovic** [bootsblogger/bootsblogger#17]
Mas, udah denger sintaks baru **Blogger** yang ini belum? Sepertinya menjanjikan.

- hxxp://www.zhinto[dot]us/2017/05/cara-membuat-readmore-versi-baru2017.html
- hxxp://www.zhinto[dot]us/2017/04/cara-baru-membuat-fitur-video-gambar-audio-postblogger.html

**Comment by igoynawamreh** [comment]
Iya mas, Bootsblogger juga sudah pakai `snippet` untuk membuat ringkasan posting:

https://github.com/bootsblogger/bootsblogger/blob/1eb59c4ef3e02fbf6af7ef3d2998a71e01414c1e/template-src/includable/post/post.snippet.xml#L5

### Snippet

**Sintaks**

Ada dua cara untuk menggunakan `snippet`.

Sintaks default:

``` html
string snippet { object }
```

Sintaks fungsional:

``` html
snippet(string, { object })
```

**Parameter**

| Parameter | Nilai | Desc |
| -------------- | ------ | --------- |
| `length` | number | Nilai minimum: `50` |
| `ellipsis` | boolean | Default: `true` |
| `linebreaks` | boolean | Default: `true` |
| `links` | boolean | Default: `true` |

**Contoh**

``` html
<b:eval expr='data:post.body snippet { length: 150 }'/>
```

``` html
<b:eval expr='snippet(data:post.body, { length: 150 })'/>
```

### Enclosure

Untuk mengaktifkan fitur: Dashboard > Settings > Other > Site feed > Enable Title Links and Enclosure Links > Yes

**Data**

``` html
{
  "type": "Blog",
  "data": {
    "posts": [
      {
        "enclosures": [
          {
            "url": value,
            "mimeType": value
          }
        ]
      }
    ]
  }
}
```

**Type/MIME**

- text
- image
- video
- audio
- application
- multipart
- message
- model

**Contoh**

``` html
<b:loop values='data:posts' var='post'>
  <b:loop values='data:post.enclosures' var='enclosure'>
    <b:if cond='data:enclosure.mimeType in {"image/jpeg", "image/gif", "image/png"}'>
      <img expr:src='data:enclosure.url'/>
    </b:if>
  </b:loop>
</b:loop>
```

**Comment by tovic** [comment]
Saya kepikiran buat bikin meta deskripsi otomatis sebenarnya, cuma sayangnya `data:post.body` hanya tersedia di dalam widget `Blog` saja.

Untuk _enclosure_ itu sepertinya menarik untuk dimanfaatkan sebagai fitur _post type_, jadi kalau ada penulis melampirkan video, musik atau gambar, nanti akan berpengaruh pada tampilan postingannya.

**Bootstrap** kan punya _carousel_, kira-kira bisa tidak semua gambar di dalam _loop_ tersebut di masukkan ke dalam _carousel_?

**Comment by tovic** [comment]
Terus untuk setiap komponen **Bootstrap** tidak bisa dibuat sebagai template terpisah saja mas? Sepertinya akan menarik:

~~~ .xml
<b:includable id='button'>
  <b:if cond='data:tag == "a"'>
    <a b:whitespace='remove' expr:class='"btn btn-" + data:kind' expr:href='data:url'>
      <data:text/>
    </a>
  <b:else/>
    <button b:whitespace='remove' expr:class='"btn btn-" + data:kind'>
      <data:text/>
    </button>
  </b:if>
</b:includable>
~~~

~~~ .xml
<b:include name='button' data='{ kind: "danger", text: "Delete"}'/>
~~~

**Comment by igoynawamreh** [comment]
> Saya kepikiran buat bikin meta deskripsi otomatis sebenarnya, cuma sayangnya data:post.body hanya tersedia di dalam widget Blog saja.

Iya mas, tapi kalau `id`, `title`, `featuredImage`, `showInlineAds` bisa didapatkan di luar widget `Blog`. Caranya:

``` html
<b:loop values='data:widgets.Blog' var='b'>
  <b:loop values='data:b.posts' var='post'>
    <p><data:post.title/></p>
  </b:loop>
</b:loop>
```

> Bootstrap kan punya carousel, kira-kira bisa tidak semua gambar di dalam loop tersebut di masukkan ke dalam carousel?

Bisa mas, gini:

``` html
<b:loop values='data:posts' var='post'>
  <div class='carousel slide' data-ride='carousel' expr:id='"Carousel_" + data:post.id'>
    <ol class='carousel-indicators'>
      <b:loop index='i' values='data:post.enclosures' var='enclosure'>
        <li expr:data-slide-to='data:i' expr:data-target='"#Carousel_" + data:post.id'>
          <b:class cond='data:i == 0' name='active'/>
        </li>
      </b:loop>
    </ol>
    <div class='carousel-inner'>
      <b:loop index='i' values='data:post.enclosures' var='enclosure'>
        <div class='carousel-item'>
          <b:class cond='data:i == 0' name='active'/>
          <b:if cond='data:enclosure.mimeType in {"image/jpeg", "image/gif", "image/png"}'>
            <img class='d-block w-100' expr:src='data:enclosure.url'/>
          </b:if>
        </div><!-- /.carousel-item -->
      </b:loop>
    </div><!-- /.carousel-inner -->
    <a class='carousel-control-prev' data-slide='prev' expr:href='"#Carousel_" + data:post.id' role='button'>
      <span aria-hidden='true' class='carousel-control-prev-icon'/>
      <span class='sr-only'>Previous</span>
    </a>
    <a class='carousel-control-next' data-slide='next' expr:href='"#Carousel_" + data:post.id' role='button'>
      <span aria-hidden='true' class='carousel-control-next-icon'/>
      <span class='sr-only'>Next</span>
    </a>
  </div><!-- /.carousel -->
</b:loop>
```

**Comment by igoynawamreh** [comment]
> Terus untuk setiap komponen Bootstrap tidak bisa dibuat sebagai template terpisah saja mas?

Iya menarik sih mas, tapi Saya berpikir kalau hanya untuk kode yang tidak terlalu sulit dan tidak terlalu panjang itu tidak perlu dijadikan sebagai template terpisah.

**Comment by tovic** [comment]
Oiya baru ingat kalau _template_ **Blogger** itu cuma satu file XML, kalau semua definisi masuk ukurannya bisa bengkak nanti! :laughing:

**Comment by irfaanprogrammer** [comment]
ya saya termasuk pengembang template blogger yang baru mungkin nanti saya akan posting semua penjelasan kodenya di blog saya, makasih mas taufik mantap webnya hehe

**Comment by irfaanprogrammer** [comment]
boleh dong mas gabung kayaknya keren projectnya hehe

**Comment by irfaanprogrammer** [comment]
kekurangan memakai kode **snippet data:post.body** adalah element tag a dan bold tidak tersaring, saya sudah mencobanya dan membuat template saya berantakan tag element bold berantakan 

saran saya memakai ini mas 
<b:eval expr='data:snippets.long snippet { length: 350, links: false, linebreaks: false, ellipsis: true }'/> 

itu dia hampir sama kaya data:post.snippet kelebihannya bisa nyaring tag a dan bold jadi bisa lebih aman ketika karakter kepotong saya dapet kode itu dari experiment saya untuk menyelesaikan tag a dan b yang tidak tersaring
