### ISSUE TITLE
Error Artikel Berubah Menjadi Bold Semua (MultipleItem)

### ISSUE THREAD

**Issue by irfaanprogrammer** [bootsblogger/bootsblogger#18]
ini contoh error menggunakan data:post.body sebagai snippet hxxps://kodeinblogger(Dot)blogspot(Dot)com (Blog saya)

**Comment by igoynawamreh** [comment]
Apa ada solusi lain selain menggunakan `data:posts[i].snippets.long`? agar semua parameter `snippet` tetap bekerja.

**Comment by irfaanprogrammer** [comment]
untuk solusi mungkin belum ada yang lain mas saya juga baru nemu cara itu sebagai penyelesaiannya, untuk menggunakannya mas harus buat kode 
```
<b:includable id='postSnippet'>
<b:comment>{postSnippet}</b:comment>
<b:eval expr='data:snippets.long snippet { length: 350, links: false, linebreaks: false, ellipsis: true }'/>
</b:includable>
```
supaya paramter snippet berkerja lalu memanggilnya dengan kode
`<b:include cond='data:post' data='post' name='postSnippet'/>`
mungkin baru itu saja mas yang saya tau soal penyelesaian error saring tag

**Comment by igoynawamreh** [comment]
Sebenarnya Saya sudah kepikiran untuk menggunakan `snippets.long`, tapi kita akan kehilangan fitur `snippet` seperti `links` dan `linebreaks`.

Oke, kita cari dulu solusinya, kalau tidak menemukan solusi lain terpaksa kita pakai cara tersebut.

**Comment by irfaanprogrammer** [comment]
kayaknya bisa make data:post.body tapi harus ada tambahan javascript untuk menghilangkan tag boldnya, mungkin itu solusi yang saya tau

**Comment by andimewa** [comment]
link download muicss udah gak ada ya bang ?

**Comment by igoynawamreh** [comment]
@irfaanprogrammer iya mas, tapi sepertinya bukan hanya tag *bold* saja yang jadi masalah, tag `a` juga sama. Untuk hal ini menurut Saya lebih baik tidak perlu menggunakan JavaScript.

**Comment by igoynawamreh** [comment]
@andimewa link download muicss?

**Comment by irfaanprogrammer** [comment]
benar sekali mas kalau make javascript kayaknya hanya akan membuat loading lebih lama, mungkin ada solusi yang lain selain itu

**Comment by igoynawamreh** [comment]
Perlu diperbaiki.

**Comment by irfaanprogrammer** [comment]
hehe iya mas saya kira ditutup aja hehe, oh ya kan template v3 itu nggak bisa makai semua fungsi mobile saya cek base templatenya ada tulisan data:view.isMobile

**Comment by igoynawamreh** [comment]
Buat *issue* baru aja mas kalau beda permasalahan, biar lebih tersusun.

**Comment by irfaanprogrammer** [comment]
tapin nggak ngaruh kok mas itu cuma ada satu doang yang buat ngelooping artikel pada widget BlogPost

**Comment by tovic** [comment]
Itu karena snippet ke-crop sampai ke tag pembuka `<b>` saja jadi HTML-nya tidak valid.

**Comment by igoynawamreh** [comment]
@tovic - sepertinya tidak ada solusi lain (tanpa JS) selain menggunakan `snippets.long`?

**Comment by tovic** [comment]
Untuk fungsional apa tidak ada semacam fungsi `strip()` di **Blogger** setara `strip_tags()` di PHP?

**Comment by igoynawamreh** [comment]
Yang Saya tau gak ada mas.

Saya lihat `super.postSnippet` juga pakai ` <data:snippets.long/>`:

``` html
<b:includable id='postSnippet'>
  <div expr:class='(data:snippetPrefix ?: "post") + "-snippet snippet-container r-snippet-container"'>
    <div class='snippet-item r-snippetized'>
      <data:snippets.long/>
    </div>
    <a class='snippet-fade r-snippet-fade hidden' expr:href='data:post.url'/>
  </div>
</b:includable>
```

**Comment by irfaanprogrammer** [comment]
sebenarnya tidak masalah juga kalau memakai data:post.body tinggal usernya aja yang menyesuaikan, kalo ada error ya tinggal dia edit lewat postingannya ditambahin space atau sejenisnya

**Comment by igoynawamreh** [comment]
Harus diperbaiki mas! Bootsblogger dirancang untuk memudahkan dan untuk siapapun.

**Comment by irfaanprogrammer** [comment]
iya benar juga, suatu saat pasti akan ketemu masalah ini kalau tidak diselesaikan, soalnya saya juga begitu pas build template v3 dan user komplen kalau tampilannya jadi berantakan
