### ISSUE TITLE
About Template Commentary Suggestions

### ISSUE THREAD

**Issue by lawpai** [bootsblogger/bootsblogger#24]
I feel this template is very good, I like it. I found this template can only use google + comment system, and can not use the blogger comes with the comment system, but I think blogger comes with the comment system has some features can not be ignored, I need to use this comment system, so I would like to ask the development Can this feature be added? Thank you for your hard work.

**Comment by ismis** [comment]
try https://github.com/bootsblogger/bootsblogger/tree/master, but bootstrap v3
