### ISSUE TITLE
New comment system as Google is shutting down Google+ for consumers

### ISSUE THREAD

**Issue by rizaumami** [bootsblogger/bootsblogger#27]
As title said, this theme is need another comment system than Google+ as [Google will shutting down Google+ for consumers](https://www.blog.google/technology/safety-security/project-strobe/).  
Perhaps by getting back using default Blogspot comment system?

**Comment by jesusferm** [comment]
I have the same problem, i am trying updated comments systems, but not work, any idea?

**Comment by igoynawamreh** [comment]
Since Bootsblogger will be based on Bloggerable, I'm currently focusing on Bloggerable. By default, Bloggerable will use the default blogspot comment system. 

Due to potential problems with the project, the target date is unrealistic. I will work hard to finish it as soon as possible.

**Comment by jesusferm** [comment]
Thank you very much @igoynawamreh for responding.
I understand the work behind it.
No problem, and thank you for the development.
