### ISSUE TITLE
CSS & JS Eksternal Bootstrap

### ISSUE THREAD

**Issue by tovic** [bootsblogger/bootsblogger#3]
Untuk CSS dan JavaScript kan sifatnya statis ya mas, apa nggak tertarik untuk pakai CDN saja, bisa bisa dicache juga nanti hasilnya.

https://www.bootstrapcdn.com

**Comment by igoynawamreh** [comment]
Sebenarnya bisa saja mas, tapi karena kode sumber CSS Bootsblogger (`scss/bootsblogger/`) memanfaatkan kode sumber Sass Bootstrap (`scss/bootstrap/`) seperti *variables* dan *mixins*, dan juga Bootsblogger dirancang untuk dapat mengubahsuaikan CSS Bootstrap langsung di dalam kode sumber Bootsblogger, jadi itu alasan tidak menggunakan CDN mas.

**Comment by tovic** [comment]
Iya-iya, mudeng sekarang.
