### ISSUE TITLE
Redesign comment form

### ISSUE THREAD

**Issue by tovic** [bootsblogger/bootsblogger#5]
Mungkin bisa dicoba dengan memasukkan HTML formulir dan pesan komentar ke dalam tab, jadi ukuran tinggi tab tidak akan masalah:

![2017-01-08_131219](https://cloud.githubusercontent.com/assets/1669261/21747741/3a87686e-d5a4-11e6-871a-e1cff1acab2b.png)

**Comment by igoynawamreh** [comment]
Keren mas, ada pull request-nya gak?

**Comment by tovic** [comment]
Enggak hehe. Lagi sibuk ngurusin Mecha.

**Comment by igoynawamreh** [comment]
Oke mas, saya coba buat. Hehe :+1: :
