### ISSUE TITLE
A few Responsiveness issues.

### ISSUE THREAD

**Issue by asharamseervi** [bootsblogger/bootsblogger#6]
A great initiative by you. I appreciate and loved your concepts & implementations.

Still, theme is under construction, even though I have to report something, which causes in mobile screen. You may have a look on live portfolio at [https://aaimaawebs.blogspot.com/](https://aaimaawebs.blogspot.com/)

Title collapse with navigation menu button.
![screenshot_2017-02-09-15-14-09](https://cloud.githubusercontent.com/assets/5942572/22778420/e0514f3e-eedc-11e6-8d1d-1271fca6ad83.png)
![screenshot_2017-02-09-15-14-15](https://cloud.githubusercontent.com/assets/5942572/22778421/e059aab2-eedc-11e6-919f-229d2c92712c.png)

**Comment by igoynawamreh** [comment]
> A great initiative by you. I appreciate and loved your concepts & implementations.

Thank you.

> Title collapse with navigation menu button.

It's a bug in the Bootstrap `v4 alpha 6`, it was already fixed in `v4 beta-1 milestone`.
